config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/', to: 'welcome#index'
  root to: 'welcome#index'

  resources :projects, only: :index
  resources :info, only: :index
  resources :contact, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
        
    end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
    def index 

    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController 

    def index 

    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 
    def index
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/index.html.erb
<h1>Always looking for awesome projects. Reach out at:</h1>

<h3>Email: mr.tonyboi@gmail.com</h3>
<h3>Twitter: </h3>
<h3>Nostr: </h3>

app/views/info/index.html.erb
<h3>I like to build things</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalWebpageRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= button_to "Home", root_path, :method => :get %>
    <%= button_to "Projects", projects_path, :method => :get %>
    <%= button_to "Info", info_index_path, :method => :get %>
    <%= button_to "Contact", contact_index_path, :method => :get %>

  </body>
</html>

app/views/projects/index.html.erb
<h1>Projects</h1>

<h4>Dude, How's My City?</h4>
<p> Allows users to compare cost of living between cities both nationally and
internationally. By using metrics suchs as average housing, food and public 
transportaion costs users are able to see whether they can comfortablly afford
to live in the area. There is also information displayed on average salaries for
various occuaptions. </p>
<p>Tech Environment: Ruby on Rails, React, PostgreSQL</p>

<h4>Waste No More</h4>
<p>Tied of throwing out expired food? This application that takes in ingredients from a users fridge and provides 
recommended recipies prioritizing food close to expiration. </p>
<p>Tech Environment: Ruby on Rails, PostgreSQL</p>

<h4>Social API</h4>
<p>This is a represention of an API used by a social media platform. It allows users to create profiles, 
post content, reply to posts, and like posts.</p>
<p>Tech Environmnet: Java, SpringBoot, PostgreSQL</p>

app/views/welcome/index.html.erb
<h1>Antonio Salmeron</h1>
<h3>Software Developer</h3>

<h3>
    Born in California 1997, I beleive software engineering can be impactful to
     communities across the globe. I enjoy pursuing open source projects with 
     and emphasis on data, privacy and payments.
</h3>